### PR TITLE
MediaQueue: Added tiggers and started off with unit-tests

### PR DESCRIPTION
**Pull request by SimonSimCity**
I did quite some changes to the MediaQueue, packed with this implemenation.

I've just added a property-changed event when `Count` or `Current`, forwarded the internal queue changes (before the `CollectionChanged` event never got triggered), fixed the randomness of the shuffle-method (according to http://stackoverflow.com/questions/767999/random-number-generator-only-generating-one-random-number#answer-768001) and started off with unit-tests - mainly for the MediaQueue implementation.

### CODE REVIEW

**Comment by SimonSimCity** [comment]
By the changes in a02c578 I opened up for a custom extension to the MediaQueue like the following:

	public class StoredMediaQueue : MediaQueue
	{
		public StoredMediaQueue(IBlobCache blobCache)
		{
			var queue = blobCache.GetOrCreateObject<ObservableCollection<IMediaFile>>(
				"Queue",
				() => new OptimizedObservableCollection<Track>()
			).Wait();

			if (queue.Count != Count)
			{
				ReplaceQueueWith(queue);
			}

			_unshuffledQueue = blobCache.GetOrCreateObject<ObservableCollection<IMediaFile>>(
				"QueueUnshuffled",
				() => null
			).Wait();

			var index = blobCache.GetOrCreateObject<int>(
				"QueueIndex",
				() => -1
			).Wait();

			if (Index != index)
			{
				SetIndexAsCurrent(index);
			}

			var repeat = blobCache.GetOrCreateObject<bool>(
				"QueueRepeat",
				() => false
			).Wait();

			PropertyChanged += (sender, e) =>
			{
				Task.Run(() =>
					{
						if (e.PropertyName == "Index")
						{
							blobCache.InsertObject<int>("QueueIndex", Index);
						}
						else if (e.PropertyName == "Shuffle")
						{
							blobCache.InsertObject<ObservableCollection<IMediaFile>>("QueueUnshuffled", _unshuffledQueue);
							blobCache.InsertObject<ObservableCollection<IMediaFile>>("Queue", _queue);
						}
						else if (e.PropertyName == "Repeat")
						{
							blobCache.InsertObject<bool>("QueueRepeat", repeat);
						}
					});
			};

			CollectionChanged += (sender, e) =>
			{
				Task.Run(() =>
					{
						if (Shuffle)
						{
							blobCache.InsertObject<ObservableCollection<IMediaFile>>("QueueUnshuffled", _unshuffledQueue);
						}

						blobCache.InsertObject<ObservableCollection<IMediaFile>>("Queue", _queue);
					});
			};
		}
	}

It stores every value of the MediaQueue in an Akavache storage and loads it back when initializing the Queue.

**Comment by martijn00** [comment]
Changes are looking good! I would like to add the test to it's own project instead of adding it to the Abstractions. Can you make that change?

**Comment by SimonSimCity** [comment]
@martijn00 They're all encapsulated in their own project, but share the same namespace - I guess that's what you dislike, right ..? 😉

**Comment by martijn00** [comment]
@SimonSimCity Yeah i was a bit confused how you named that. I've merged this, and fixed the location and naming in a new commit. I'm also wondering why you choose Nunit 2.6.4 instead of the much newer 3.5.0? Is it an idea to use Moq instead of the MediaFile you added now?

**Comment by SimonSimCity** [comment]
Not really .. `2.6.4` was just part of the template I used for creating the project. Using Moq instead of an implementation of MediaFile could also have it's pro's. I just decided to go this way because it was a step that was easy to take.

**Pull request merged**
