### PR TITLE
Get solution to compile (hopefully)

### PR DESCRIPTION
**Pull request by myrobotzone**
Added poject.json file to MediaManager.UWP.csproj, which should fix the compilation problem (at least locally after a couple of rebuilds the entire solution complies)

### CODE REVIEW

**Comment by myrobotzone** [comment]
I just noticed the CI build is still failing. I was able to reproduce the same error. Deleting the files below seemed to fix the problem (I hate when stuff like this blocks productive development):

* MediaManager.Forms/MediaManager.Forms.UWP/Plugin.MediaManager.Forms.UWP.nuget.props
* MediaManager.Forms/MediaManager.Forms.UWP/Plugin.MediaManager.Forms.UWP.nuget.targets
* MediaManager.Forms/MediaManager.Forms.UWP/Plugin.MediaManager.XamarinForms.UWP.nuget.targets

**Comment by martijn00** [comment]
This is not the correct fix. We should switch fully to packagereference or project json. Not have a combination of the 2. I would think we should go to packagereference.

**Comment by myrobotzone** [comment]
Package reference makes sense. MS is dropping project.json.

**Comment by myrobotzone** [comment]
Do you know of anyone is working on getting the solution to compile? I think getting the CI green has top priority. Otherwise we risk accumulating breaking changes.

**Comment by myrobotzone** [comment]
I took another quick look at this. While in the long run it makes sense to move to msbuild, it looks like quite a big job: 

> If you been given the unenviable task of migrating your .NET Core project from ‘project.json’ to MSBuild (csproj), you are likely to find your muscle memory disrupted and the documentation lacking (copied from http://www.natemcmaster.com/blog/2017/03/09/vs2015-to-vs2017-upgrade/)

So I sugget that for the short term, we get all projects working with project.json. The following link is .net core related, but it kinda looks like the three files I've mentioned above shouldn't be under source control: https://stackoverflow.com/questions/43069745/should-nuget-props-and-targets-files-be-part-of-the-source-code-repository

I'm by no means an expert in the area, but are you sure that deleting the three files isn't an acceptable short term solution?

**Comment by martijn00** [comment]
Deleting the 3 files doesn't revert to project.json. I agree on that reverting everything back to that might be a better short term solution.

**Comment by myrobotzone** [comment]
No that's clear, but deleting the files and ignoring them will at least get the solution into a state where all projects build for all people who get the latest source. A solution that doesn't compile is not a good look.

**Pull request merged**
