### PR TITLE
Support VS Mac multi-targeting in the editor

### PR DESCRIPTION
**Pull request by mrward**
Lower cased target frameworks in Directory.Build.props and
MediaManager.csproj. It looks like MSBuild.Sdk.Extras lower cases
this at some point and it affects the evaluated properties from
Directory.Build.props and the evaluated item groups in MediaManager.
This problem also affects MSBuild on the Mac command line.

Added some None remove items for Compile items that are added for
each platform. VS Mac does not ignore these duplicate None items and
this can break code completion since the None item is used since it
is first in the list of items.

Not changed the other projects just MediaManager. Other projects
use mixed case for the target frameworks.

### CODE REVIEW

**Comment by martijn00** [comment]
Looks good to me. Happy to merge this in if you agree.

**Comment by mrward** [comment]
I will update the other projects and do some more testing with VS Mac.

**Comment by martijn00** [comment]
Thanks! Since this sort of structure is also used in a lot of other projects like Lottie and MvvmCross, we should probably inform people and make the changes there as well.

**Comment by mrward** [comment]
I am going to file a bug against VS Mac about the None items breaking code completion. I think VS Mac should be a bit smarter here and handle a C# file being both a None item and a Compile item.

We would still have the problem of the Solution window showing duplicate items, but at least code completion would not be broken.

**Pull request merged**
