### PR TITLE
MediaManager.UWP now provides support for Play/Pause, Next and Previous media buttons

### PR DESCRIPTION
**Pull request by myrobotzone**
This was tested on Win 10 using bluetooth speakers with physical media buttons.

Changes:
- Added RemoteControlNotificationHandler, including unit test project and system wrappers that abstract dependencies
- Integrated RemoteControlNotificationHandler with the MediaManagerImpementation for UWP.

### CODE REVIEW

**Comment by martijn00** [comment]
Looks good! The main code base could also benefit much from unit tests like yours! It would be so nice if you could contribute on that!

**Comment by myrobotzone** [comment]
Thanks. I appreciate the rapid responses :-)

**Comment by martijn00** [comment]
@myrobotzone I just have some trouble with the CI now because you used the new PackageReference csproj format. I'll see if i can fix that.

**Comment by myrobotzone** [comment]
Yeah sorry about that. After synching, I noticed the packages.json file
isn't included in the Plugin.MediaManager.uwp proj. Including it and doing
a package restore got it working in my local environment.

On 31/07/2017 9:43 am, "Martijn van Dijk" <notifications@github.com> wrote:

@myrobotzone <https://github.com/myrobotzone> I just have some trouble with
the CI now because you used the new PackageReference csproj format. I'll
see if i can fix that.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/martijn00/XamarinMediaManager/pull/227#issuecomment-318993177>,
or mute the thread

**Comment by myrobotzone** [comment]
To avoid such differences in project files, what do you think about all contributors using the same version of Visual Studio? I'm happy to switch to the version you are using (is it 2015?).

**Comment by martijn00** [comment]
@myrobotzone I'm using VisualStudio for Mac in daily development, but also got VS2017 to build and work on UWP. Since PackageReference will be used in .NET Standard anyways i think it is a good idea to switch to it soon. The first task to make this possible would be converting all UWP sample projects to this. This will make the CI build again. I much bigger task later on will be to convert to .NET Standard.

**Pull request merged**
