### PR TITLE
Fixed issue where buffering would always be zero.

### PR DESCRIPTION
**Pull request by fela98**

### CODE REVIEW

**Comment by modplug** [comment]
Many of these issues exist in the Video player implementation as well since the video player is an adoption of the audio player. Can you fix this in the Video player as well?

**Comment by fela98** [comment]
We should seriously create a base class for audio and video.

**Comment by modplug** [comment]
AFAIK the only difference between them is the set video surface methods. The rest should be more or less equal and can be extracted to a base class for iOS

**Comment by fela98** [comment]
I'm just adding the fix for the VideoPlayerImplementation for now, refactoring and creating a base class should be done in a separate pull request IMO.

**Comment by modplug** [comment]
Agreed

**Pull request merged**
