### PR TITLE
Get it to compile

### PR DESCRIPTION
**Pull request by myrobotzone**
Using Visual Studio 2017, updated all Nuget packages (except ExoPlayer which has breaking API changes). MediaForms.UDP now builds and runs (fixed this by modifying both MediaForms and MediaForms.UDP projects, so that they reference their required dlls directly).

This fixes issue #81

P.S. this is my first pull request and I'm kinda new to git so let me know if I'm doing something wrong.

### CODE REVIEW

**Comment by martijn00** [comment]
Looks good! Only thing missing is updated nuspec files. I can do that.

For future pull requests make sure you rebase on the latest develop and don't do any merge commits to avoid many commits.

**Comment by myrobotzone** [comment]
Wow, your fast! Thanks for the tips. I think with the help of Google I should be able to work it out. Not sure, but the PR may also fix issue #208.

**Comment by martijn00** [comment]
@myrobotzone  Thanks! I've also updated Appveyor so it will now run on every PR and make nightly builds again! Feel free to make more PR's with improvements!

**Comment by myrobotzone** [comment]
Great - it's always nice to see green builds. Cool, I'm looking into an improvement - media button support on UWP for previous and next buttons (I think currently only play and pause are supported).

**Pull request merged**
