### PR TITLE
A couple Android fixes

### LINKED ISSUE #87: Android: "Handle must be valid" exception in MediaSessionManager.UpdatePlaybackState()
I have been getting this exception in MediaSessionManager.UpdatePlaybackState(), in the call to MediaSessionCompat.SetPlaybackState().

According to [this report](https://bugzilla.xamarin.com/show_bug.cgi?id=47577), This appear to be a Xamarin garbage collection bug.

I have fixed this using the temporary solution listed in that report. Pull request to come soon.

### PR DESCRIPTION
**Pull request by jmartine2**
1) Removed exception thrown by MediaManagerBase.CurrentPlaybackManager getter, and allowed it to return null instead. Added null reference checks to code that accessed getter. #76 

2) Modified MediaPlayerService.Play() so that if there is an IllegalStateException thrown by _mediaPlayer.PrepareAsync(), it retries several times.

3) Modified MediaPlayerService.SetMediaPlayerDataSource() to avoid some exceptions.

4) Fixed #87

### CODE REVIEW

**Comment by SimonSimCity** [comment]
For option 2 ... have you analyzed why this exception is thrown? Are there maybe different `IllegalStateException`s that are thrown here that should be handled in a certain way, or is the silver bullet just to reset the player and retry?

**Comment by jmartine2** [comment]
@SimonSimCity I never found out for sure why the exception was being thrown. Originally, the exception was causing my application to simply crash because the exception was unhandled. My first try at fixing it was to catch it and try just one more time immediately. This prevented the crash and reduced the frequency of the issue, but still occasionally the second try would fail. Since I added the retry loop with a delay, the issue has not reoccurred for me. My best guess is that it is a timing issue, where something is not quite ready for PrepareAsync, but I don't know enough about the internals of Android media to know for sure.

**Comment by SimonSimCity** [comment]
👍  nice! I just wanted to have this written somewhere that we actually tested it and care about the code we write. Because what ends up here is unlikely to be changed if we do not get an exception at a later state :wink:

**Comment by jmartine2** [comment]
@martijn00 , This pull request included a new file that I added called Environment.txt (see "Files Changed"). However, it appears that when you merged it, that file didn't make it into the master repository. Do you know why that would be? Can you look into it?

**Comment by martijn00** [comment]
I removed that file after merging. Why would we use the old mono bridge-implementation?

**Comment by jmartine2** [comment]
@martijn00 , because it is the fix for issue #87. Please see [https://bugzilla.xamarin.com/show_bug.cgi?id=47577](https://bugzilla.xamarin.com/show_bug.cgi?id=47577)

**Pull request merged**
