### PR TITLE
Added SetAutoPlayNext feature and fix Android sample app and fix ExoPlayer paths

### PR DESCRIPTION
**Pull request by jmartine2**
Added a function to IMediaManager and MediaManagerBase to specify whether or not to automatically play the next MediaFile when the current one ends. I left the default as True (if you don't use the function) in order to not break existing usages.

### CODE REVIEW

**Comment by fela98** [comment]
To be honest, this doesn't really make sense to me. Why not simply add a single item to the queue at once? Or use OnStatusChanged to pause it whenever the previous one finishes. IMO the behaviour should always be that it plays the next item of the queue automatically, anything else wouldn't make sense for the user.

**Comment by jmartine2** [comment]
Also fixed sample app to make notification bar buttons work.

**Comment by fela98** [comment]
I still think that this should not become merged. We should rather fix the bugs that you describe as 'very strange behavior'.

**Comment by jmartine2** [comment]
I don't think that they are bugs. They are normal behavior for an app that wants to use the queue. The undesired behavior is caused by my app trying to play its next song choice at the same time that PlayNext() is doing its things:

```
await PrepareCurrentAndThen(async () =>
{
   await CurrentPlaybackManager.Play();        
   await CurrentPlaybackManager.Pause();
   await Seek(TimeSpan.Zero);
});

```

If these things are happening and I'm trying to start a whole new song at the same time, it leads to race conditions. I don't know of any way to prevent this from happening, other than preventing PlayNext() from being called. If you have any other ideas, I'm open.

**Comment by martijn00** [comment]
I've cherry picked 2 of your fixes. I am really not sure if the `SetAutoPlayNext` feature is a good idea. I need some time to look into how to best handle that scenario.

Can you provide those fixes in separate PR's next time?

Thanks!

**Comment by martijn00** [comment]
Can you rebase from the upstream develop, so this at least is possible to merge later?

**Comment by jmartine2** [comment]
I'd be happy to submit separate PR's if I could. GitHub won't seem to let
me. If I have an existing PR that hasn't been merged yet, and I try to
create a new PR, all I get is a green button that says, "View Pull
Request", and it takes me to my existing PR to edit. If you know of a way
to make them separate PR's, I'd love to learn how, and will do it in the
future.

**Pull request closed without merging**
