### PR TITLE
Fixed issues #8 and #9

### PR DESCRIPTION
**Pull request by jmartine2**
Fixed issues #8 (Android: StatusChanged event does not get fired when regaining audio focus.) and #9 (Android: If audio is paused by user, other device sounds cause it to unpause.)

### CODE REVIEW

**Comment by martijn00** [comment]
Thanks! Can you merge upstream into your branch so i can merge this?

**Comment by jmartine2** [comment]
Martijn,

I am very new to GitHub, and I'm not sure what you mean. Can you explain
more what you mean by "merge upstream into your branch"?

-Joe

On Mon, Aug 22, 2016 at 11:59 PM, Martijn van Dijk <notifications@github.com

**Comment by SimonSimCity** [comment]
@jmartine2 Here's a quick guideline of how to do it using the command line: https://help.github.com/articles/syncing-a-fork/

Or if you're neither used to the command line and using SourceTree, try this: http://stackoverflow.com/questions/13273852/how-do-i-update-my-forked-repo-using-sourcetree

Both are doing the same job - the second one is a more graphical way of doing it.

**Comment by jmartine2** [comment]
Ok, but I'm not sure why I would need to do this. I believe that my
modifications were made to Martijn's Master source. When I submitted the
pull request, and looked at the Diff, I didn't see any differences between
my source and Martijn's master, other than the changes that I made. Am I
missing something?

**Comment by martijn00** [comment]
If you look at your fork, and then the branch you made the pull request on, you'll see `This branch is 1 commit ahead, 9 commits behind martijn00:master.` Like @SimonSimCity says, you need to merge my `martijn00:master` into your `jmartine2:master` and resolve any merge conflicts. After that this pull request will update itself automatically and i will be able to merge it.

**Comment by jmartine2** [comment]
Ok, I think I finally figured it out and was able to merge the changes without conflicts. I built the merged solution, and I got errors because in the Windows projects did not implement the interface, so I let VS create the default implementations (throw NotImplementedException), and then the project was able to build.  It appears to work.  I have pushed these changes to my respository as well.

**Comment by martijn00** [comment]
@jmartine2 New release is up on Nuget

**Pull request merged**
